import { Metadata } from "next";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import ThemeProvider from "../providers/ThemeProvider";
import { ToastContainer } from "react-toastify";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import Script from "next/script";
import { getNewRelicBrowserScript } from "../lib/newrelic-browser";
import { Provider } from "react-redux";
import store from "../lib/store";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const newrelicBrowserScript = getNewRelicBrowserScript();
  return (
    <html lang="en">
      <body>
        {newrelicBrowserScript && (
          <Script
            id="newrelic-browser"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{ __html: newrelicBrowserScript }}
          />
        )}
        <Provider store={store}>
          <AppRouterCacheProvider>
            <ReactQueryProvider>
              <ThemeProvider>
                {children}
                <ToastContainer />
              </ThemeProvider>
            </ReactQueryProvider>
          </AppRouterCacheProvider>
        </Provider>
      </body>
    </html>
  );
}
