import type { Metadata } from "next";
import ThemeProvider from "../../providers/ThemeProvider";
import { Box, Container } from "@mui/material";
import Header from "../../components/layout/home/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  Aside,
  RightColumn,
}: Readonly<{
  Aside: React.ReactNode;
  RightColumn: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header />

          <Container
            maxWidth="xl"
            sx={{
              display: "flex",
              flex: 1,
              flexDirection: { xs: "column", lg: "row" },
              px: 0,
              mx: -3,
            }}
          >
            {/* Aside section */}
            <Box
              component="aside"
              sx={{
                width: { xs: "100%", lg: "30%" },
                display: "flex",
                flexDirection: "column",
              }}
            >
              {Aside}
            </Box>

            {/* Right column section */}
            <Box
              component="main"
              sx={{
                width: { xs: "100%", lg: "70%" },
                display: "flex",
                flexDirection: "column",
              }}
            >
              {RightColumn}
            </Box>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
